### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [BayshoreNetworks/yextend#4]
Hi:
Have you considered using the same license as yara proper, i.e. Apache 2.0?
Thanks for your kind consideration!

**Comment by pombredanne** [comment]
the reason why I am asking is that I wrote a generic unarchiver that builds on libarchive and 7zip here https://github.com/nexB/scancode-toolkit/tree/develop/src/extractcode

**Comment by dre** [comment]
Hey, thx for the note and apologies for taking so long to respond. Been head down working ...

Give us a few days to digest the change and I will let you know here. I don't see it as a big deal but I need to run it by a few people here at Bayshore in order to make sure everyone is ok with the change.

**Comment by pombredanne** [comment]
@dre thanks for chiming in!

**Comment by pombredanne** [comment]
@dre FWIW, in a related domain (but Python-based) https://github.com/Changaco/python-libarchive-c was recently re-released from GPL to Public Domain

**Comment by pombredanne** [comment]
@dre any update?

**Comment by dre** [comment]
License has been updated and should be reflected on next release

**Comment by pombredanne** [comment]
@dre Thank you very much for following up my Lord!
